//! Display an iTerm2 inline image through the identity-gated session emit.
//!
//! This is the identity-keyed counterpart of `kitty_graphics.rs`: iTerm2's protocol has no
//! support query, so instead of probing, the capability probe infers support from the terminal's
//! resolved identity — `Capabilities::iterm2_images` is a known `true` only under iTerm2 or
//! `WezTerm` (which speaks the protocol too), and honestly *unknown* everywhere else. The
//! session emit `TerminalSession::inline_iterm2_image` refuses to write a byte unless the
//! finding affirms support (R-CAP-4), so the OSC 1337 payload never lands on a terminal that
//! nothing said can render it. Inline bytes open no resource, so no policy gate is involved
//! (unlike the kitty file/temp-file/shared-memory transmissions).
//!
//! Run under iTerm2 or `WezTerm` to see a small gradient image; under anything else it explains
//! the unknown finding and prints the escaped bytes it would have sent:
//!
//! ```sh
//! cargo run --example iterm2_inline_image
//! ```

#[cfg(unix)]
fn main() -> qwertty::Result<()> {
    use std::time::Duration;

    use qwertty::commands::graphics::iterm2::{self, Dimension};
    use qwertty::{CommandBuffer, TerminalSession};

    // A 16x16 RGB PNG (an orange-to-blue diagonal gradient), 212 bytes. The caller always hands
    // qwertty an already-encoded image file — qwertty takes no image dependency (R-OUT-1). This
    // one was generated by a short deterministic script (zlib-compressed 8-bit RGB scanlines,
    // filter 0) and verified to decode; any PNG/JPEG/GIF bytes work the same way.
    const TINY_PNG: &[u8] = &[
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, //
        0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x10, //
        0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x91, 0x68, 0x36, 0x00, 0x00, 0x00, //
        0x9b, 0x49, 0x44, 0x41, 0x54, 0x78, 0xda, 0x63, 0xf8, 0xcf, 0xe0, 0xf0, //
        0x8d, 0xc5, 0xed, 0x1d, 0x87, 0xcf, 0x53, 0x9e, 0xe0, 0xbb, 0x82, 0x91, //
        0x57, 0x44, 0xe3, 0xcf, 0x48, 0xa6, 0x1d, 0x96, 0xcd, 0xd9, 0xad, 0x54, //
        0xb4, 0x49, 0xad, 0x72, 0x95, 0x56, 0xfd, 0x42, 0xbd, 0xb6, 0x99, 0xc6, //
        0x3d, 0x13, 0xcc, 0x27, 0x75, 0x58, 0xcf, 0xac, 0x77, 0x98, 0xcf, 0x40, //
        0x92, 0xea, 0x72, 0x97, 0xa5, 0x0c, 0x24, 0xa9, 0xce, 0xf3, 0x58, 0xc3, //
        0x40, 0x92, 0xea, 0x34, 0x9f, 0x4d, 0x0c, 0x24, 0xa9, 0x8e, 0x0d, 0xdc, //
        0xc1, 0x40, 0x92, 0xea, 0xd0, 0xd0, 0xfd, 0x0c, 0x24, 0xa9, 0xf6, 0x89, //
        0x3c, 0xca, 0x40, 0x92, 0x6a, 0x97, 0xd8, 0x33, 0x0c, 0x24, 0xa9, 0xb6, //
        0x4e, 0xba, 0xc4, 0x40, 0x92, 0x6a, 0xa3, 0xb4, 0x1b, 0x0c, 0x24, 0xa9, //
        0xd6, 0xca, 0xba, 0xcf, 0x40, 0x92, 0x6a, 0xc5, 0xbc, 0xa7, 0x0c, 0x24, //
        0xa9, 0x96, 0x2c, 0x7e, 0xcd, 0x40, 0x92, 0x6a, 0x81, 0xf2, 0x4f, 0x0c, //
        0x24, 0xa9, 0xe6, 0xa8, 0xfe, 0xc1, 0x40, 0x9a, 0xea, 0x86, 0xff, 0x00, //
        0x65, 0xbc, 0x5d, 0xcb, 0x03, 0xec, 0xcd, 0x16, 0x00, 0x00, 0x00, 0x00, //
        0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
    ];

    // Opening the session enters raw mode; the restore handle covers panics below.
    let mut session = TerminalSession::open()?;
    let restore = session.restore_handle();
    let previous = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |info| {
        _ = restore.restore();
        previous(info);
    }));

    // The same DA1-fenced probe bundle as everywhere else. The iTerm2 finding costs the bundle
    // nothing extra: it is inferred from the identity the probe resolves anyway (XTVERSION when
    // answered, environment otherwise).
    let capabilities = session.probe_capabilities(Duration::from_millis(150))?;
    let support = capabilities.iterm2_images.clone();

    if support.value_copied() == Some(true) {
        // Affirmed (identity-inferred): emit the image through the gated session helper, sized
        // in cells so it stays small regardless of the terminal's cell pixel size.
        session
            .inline_iterm2_image_sized(&support, TINY_PNG, Dimension::Cells(8), Dimension::Auto)?
            .text("\r\n")?
            .flush()?;
        session.leave()?;
        println!(
            "rendered a 16x16 inline PNG (support: {:?} via {:?})",
            support.value_copied(),
            support.evidence(),
        );
        return Ok(());
    }

    // Not affirmed: the gate would refuse (CapabilityUnverified) and write nothing, so show what
    // *would* have been sent instead. Unknown is not unsupported (FM-C4) — under a multiplexer or
    // an unrecognized terminal this is the honest answer, and a caller that has verified
    // rendering out of band can construct its own finding to use as the gate.
    session.leave()?;
    println!(
        "iTerm2 inline-image support not affirmed (finding: {:?}, evidence: {:?});\n\
         not emitting. The bytes a supporting terminal would receive:",
        support.value_copied(),
        support.evidence(),
    );
    let bytes = CommandBuffer::new()
        .command(iterm2::inline_image_sized(
            b"\x00\x00\x00",
            Dimension::Cells(8),
            Dimension::Auto,
        ))
        .as_bytes()
        .to_vec();
    println!("{}", escape_for_display(&bytes));
    Ok(())
}

/// Renders control bytes readably: `ESC` as `\e`, other non-printables as `\xNN`, the rest literal.
#[cfg(unix)]
fn escape_for_display(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    let mut out = String::new();
    for &byte in bytes {
        match byte {
            0x1b => out.push_str("\\e"),
            0x20..=0x7e => out.push(byte as char),
            other => {
                let _ = write!(out, "\\x{other:02x}");
            }
        }
    }
    out
}

#[cfg(not(unix))]
fn main() {
    // Raw mode, poll(2), and the blocking query driver are Unix-only in qwertty today.
    eprintln!("this example requires Unix because live terminal sessions are Unix-only today");
}
