//! The published conformance reference: `qdb generate reference` renders the committed tree under
//! `docs/reference/generated/` — a support matrix, a compact summary, and one page per sequence
//! family carrying the entries, their citations and fixtures, and the captured conformance
//! verdicts. This is the "caniuse + MDN for terminals" face of the database.
//!
//! Output is deterministic (families and entries in `Database` order, refs to stable citations,
//! targets sorted by name), so the tree can be committed and a CI freshness check (`generate
//! --check reference`) can pin it. docs.rs cannot run `qdb`, so committed artifacts + a freshness
//! check is the publication mechanism (playbook §9).

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::matrix;
use crate::model::{Database, Family, ResultRow, ResultsFile, Sequence};

/// The directory (repo-relative) the reference tree is written to.
pub const OUTPUT_DIR: &str = "docs/reference/generated";

/// Renders the whole reference tree: a `(file_name, contents)` pair per generated file, relative to
/// [`OUTPUT_DIR`]. Deterministic and self-contained — the caller writes or diffs each file.
///
/// The set is: `README.md` (the index), `matrix.md` (the full support matrix), `summary.md` (the
/// compact docs.rs page), and one `<family>.md` per family.
#[must_use]
pub fn reference(db: &Database, results: &[ResultsFile]) -> Vec<(String, String)> {
    let mut pages = Vec::new();
    pages.push(("README.md".to_string(), render_index(db)));
    pages.push(("matrix.md".to_string(), matrix::render(db, results)));
    pages.push((
        "summary.md".to_string(),
        matrix::render_summary(db, results),
    ));
    for family in &db.families {
        pages.push((
            format!("{}.md", family.name),
            render_family(db, family, results),
        ));
    }
    pages
}

/// The banner every generated page carries, naming the command that (re)writes it.
fn banner(source: &str) -> String {
    format!("<!-- Generated by `qdb generate reference` from {source}. Do not edit by hand. -->")
}

/// Renders the index page linking the matrix, summary, and every family page.
fn render_index(db: &Database) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Terminal conformance reference");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "{}",
        banner("the sequence database and `db/results/*.toml`")
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "The generated \"caniuse + MDN for terminals\" reference: what each control sequence is,\n\
         where it is specified, and what real terminals actually did when probed. Support claims\n\
         are live-capture evidence, never hand-assertion (design 05)."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "- [Support matrix](matrix.md) — per-sequence verdicts across every captured target."
    );
    let _ = writeln!(
        out,
        "- [Conformance summary](summary.md) — per-family answered/total counts."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Families");
    let _ = writeln!(out);
    for family in &db.families {
        let _ = writeln!(out, "- [`{0}`]({0}.md)", family.name);
    }
    trim_trailing(out)
}

/// Renders one family's markdown reference page: each entry with its citations, fixtures, and —
/// for queryable entries — the per-target conformance verdicts.
#[must_use]
pub fn render_family(db: &Database, family: &Family, results: &[ResultsFile]) -> String {
    // Index each target's rows by entry id once, sorted by target name for determinism.
    let mut targets: Vec<&ResultsFile> = results.iter().collect();
    targets.sort_by(|a, b| a.target.cmp(&b.target));
    let rows_by_target: Vec<(&str, BTreeMap<&str, &ResultRow>)> = targets
        .iter()
        .map(|t| {
            (
                t.target.as_str(),
                t.results.iter().map(|r| (r.id.as_str(), r)).collect(),
            )
        })
        .collect();

    let mut out = String::new();
    let _ = writeln!(out, "# `{}` sequences", family.name);
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", banner(&format!("`db/{}.toml`", family.name)));
    for entry in &family.entries {
        let _ = writeln!(out);
        render_entry(db, entry, &rows_by_target, &mut out);
    }
    trim_trailing(out)
}

/// Renders one entry into `out`.
fn render_entry(
    db: &Database,
    entry: &Sequence,
    rows_by_target: &[(&str, BTreeMap<&str, &ResultRow>)],
    out: &mut String,
) {
    let _ = writeln!(out, "## {} (`{}`)", entry.name, entry.id);
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", entry.description);
    let _ = writeln!(out);
    let _ = writeln!(out, "- Direction: {}", entry.direction);
    if let Some(syntax) = &entry.syntax {
        let _ = writeln!(out, "- Syntax: `{syntax}`");
    }
    if let Some(responds) = &entry.responds {
        let _ = writeln!(out, "- Responds with: `{responds}`");
    }
    if !entry.params.is_empty() {
        let params: Vec<String> = entry
            .params
            .iter()
            .map(|p| {
                let kind = p
                    .kind
                    .as_ref()
                    .map(|k| format!(" ({k})"))
                    .unwrap_or_default();
                let default = p
                    .default
                    .as_ref()
                    .map(|d| format!(", default {d}"))
                    .unwrap_or_default();
                format!("`{}`{kind}{default}", p.name)
            })
            .collect();
        let _ = writeln!(out, "- Params: {}", params.join(", "));
    }
    if !entry.refs.is_empty() {
        let cites: Vec<String> = entry
            .refs
            .iter()
            .map(|r| match db.sources.get(&r.doc) {
                Some(src) => {
                    let loc = r
                        .section
                        .as_ref()
                        .map(|s| format!(" §{s}"))
                        .or_else(|| r.anchor.as_ref().map(|a| format!(" #{a}")))
                        .unwrap_or_default();
                    format!(
                        "[{}]({}){loc} (retrieved {})",
                        src.title, src.url, src.retrieved
                    )
                }
                None => format!("`{}` (unresolved)", r.doc),
            })
            .collect();
        let _ = writeln!(out, "- References: {}", cites.join("; "));
    }
    if !entry.fixtures.is_empty() {
        // Pages live at docs/reference/generated/<family>.md — three levels below the repo root —
        // so a fixture at fixtures/<...> links back through `../../../`.
        let links: Vec<String> = entry
            .fixtures
            .iter()
            .map(|f| format!("[`{f}`](../../../{f})"))
            .collect();
        let _ = writeln!(out, "- Fixtures: {}", links.join(", "));
    }
    if let Some(notes) = &entry.notes {
        let _ = writeln!(out, "- Notes: {notes}");
    }
    // Conformance line, only for queryable entries (a `responds` query the runner can probe):
    // every captured target's verdict, or `—` where a target has no result for it.
    if entry.responds.is_some() && entry.replay == "safe" && !rows_by_target.is_empty() {
        let cells: Vec<String> = rows_by_target
            .iter()
            .map(|(name, rows)| format!("{name} {}", verdict_text(rows.get(entry.id.as_str()))))
            .collect();
        let _ = writeln!(out, "- Conformance: {}", cells.join("; "));
    }
}

/// The human verdict text for one target's row (or a dash when it has no result for the entry).
fn verdict_text(row: Option<&&ResultRow>) -> String {
    match row {
        None => "—".to_string(),
        Some(row) => match row.verdict.as_str() {
            "supported" => format!("supported ({})", row.reply_len),
            "skipped" => match &row.skipped_class {
                Some(class) => format!("skipped ({class})"),
                None => "skipped".to_string(),
            },
            other => other.to_string(),
        },
    }
}

/// Trims a rendered page to exactly one trailing newline (markdownlint's no-multiple-blanks rule).
fn trim_trailing(mut s: String) -> String {
    while s.ends_with("\n\n") {
        s.pop();
    }
    s
}
