//! Documentation generation: one markdown reference page per family.
//!
//! Output is deterministic (entries render in file order, refs resolve to stable citations),
//! so the generated tree can be committed or diffed in CI. This first cut proves the docs
//! pipeline; publication wiring lands later.

use std::fmt::Write as _;

use crate::model::{Database, Family, Sequence};

/// Renders a `(relative_path, contents)` pair for each family page.
#[must_use]
pub fn pages(db: &Database) -> Vec<(String, String)> {
    db.families
        .iter()
        .map(|family| (format!("{}.md", family.name), render_family(db, family)))
        .collect()
}

/// Renders one family's markdown reference page.
#[must_use]
pub fn render_family(db: &Database, family: &Family) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# `{}` sequences", family.name);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by `qdb generate` from `db/{}.toml`. Do not edit by hand.",
        family.name
    );
    for entry in &family.entries {
        let _ = writeln!(out);
        render_entry(db, entry, &mut out);
    }
    out
}

/// Renders one entry into `out`.
fn render_entry(db: &Database, entry: &Sequence, out: &mut String) {
    let _ = writeln!(out, "## {} (`{}`)", entry.name, entry.id);
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", entry.description);
    let _ = writeln!(out);
    let _ = writeln!(out, "- Direction: {}", entry.direction);
    if let Some(syntax) = &entry.syntax {
        let _ = writeln!(out, "- Syntax: `{syntax}`");
    }
    if let Some(responds) = &entry.responds {
        let _ = writeln!(out, "- Responds with: `{responds}`");
    }
    if !entry.params.is_empty() {
        let params: Vec<String> = entry
            .params
            .iter()
            .map(|p| {
                let kind = p
                    .kind
                    .as_ref()
                    .map(|k| format!(" ({k})"))
                    .unwrap_or_default();
                let default = p
                    .default
                    .as_ref()
                    .map(|d| format!(", default {d}"))
                    .unwrap_or_default();
                format!("`{}`{kind}{default}", p.name)
            })
            .collect();
        let _ = writeln!(out, "- Params: {}", params.join(", "));
    }
    if !entry.refs.is_empty() {
        let cites: Vec<String> = entry
            .refs
            .iter()
            .map(|r| match db.sources.get(&r.doc) {
                Some(src) => {
                    let loc = r
                        .section
                        .as_ref()
                        .map(|s| format!(" §{s}"))
                        .or_else(|| r.anchor.as_ref().map(|a| format!(" #{a}")))
                        .unwrap_or_default();
                    format!(
                        "[{}]({}){loc} (retrieved {})",
                        src.title, src.url, src.retrieved
                    )
                }
                None => format!("`{}` (unresolved)", r.doc),
            })
            .collect();
        let _ = writeln!(out, "- References: {}", cites.join("; "));
    }
    if let Some(notes) = &entry.notes {
        let _ = writeln!(out, "- Notes: {notes}");
    }
}
