//! The caniuse support matrix: a rendering of `db/results/<target>.toml` (design 05, "Support
//! status = conformance results, not registry fields").
//!
//! Rows are the queryable sequences — entries with a `responds` link and `replay = "safe"` —
//! grouped by family in file order. Columns are capture targets, sorted by name. A cell reports the
//! support verdict that target recorded (results schema v2): supported (with reply length),
//! unsupported, no-reply, unprobeable, or a dash when the target has no result for the entry. The
//! matrix claims nothing about targets it never captured: **evidence, not inference** (design 05's
//! "machines write support claims" principle, made visual).
//!
//! Output is deterministic — families and entries render in `Database` order (file order), targets
//! sorted by name — so a golden test can pin it and `qdb generate --check` can detect drift.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::model::{Database, ResultRow, ResultsFile};

/// One row's outcome for one target, or `None` if that target has no result for this entry at all
/// (never probed / no results file present).
type Cell<'a> = Option<&'a ResultRow>;

/// A target's capture is marked stale once it falls this many days behind the freshest capture in
/// the set. The threshold is *data-relative* (compared against the newest capture date, never the
/// wall clock) so the render stays deterministic: an attended cell goes stale as the headless
/// targets are re-run, not as calendar time passes on a machine that never regenerates.
const STALE_DAYS: i64 = 180;

/// Renders the full caniuse support matrix as Markdown.
///
/// `results` should be every loaded `db/results/<target>.toml` file (order does not matter; this
/// function sorts targets by name for determinism).
#[must_use]
pub fn render(db: &Database, results: &[ResultsFile]) -> String {
    let mut targets: Vec<&ResultsFile> = results.iter().collect();
    targets.sort_by(|a, b| a.target.cmp(&b.target));

    // Index each target's rows by probed entry id for O(1) cell lookup.
    let rows_by_target: Vec<BTreeMap<&str, &ResultRow>> = targets
        .iter()
        .map(|t| t.results.iter().map(|r| (r.id.as_str(), r)).collect())
        .collect();

    let mut out = String::new();
    render_header(&mut out, &targets);
    render_legend(&mut out);

    for family in &db.families {
        let queryable: Vec<&crate::model::Sequence> =
            family.entries.iter().filter(|e| is_queryable(e)).collect();
        if queryable.is_empty() {
            continue;
        }
        let _ = writeln!(out, "## `{}`", family.name);
        let _ = writeln!(out);
        render_table_header(&mut out, &targets);
        for entry in &queryable {
            render_row(&mut out, entry, &rows_by_target);
        }
        let _ = writeln!(out);
    }

    // Each family block ends with a blank separator line; trim the last one so the file ends
    // with exactly one trailing newline (markdownlint's no-multiple-blanks rule).
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

/// An entry is a matrix row iff a capture can actually probe it: it has a `responds` link (it is a
/// query) and it is `replay = "safe"` (queries only — mirrors `capture::ProbePlan::build`'s safety
/// gate; `modal`/`destructive` entries never reach a live terminal blind and so never appear in a
/// results file).
fn is_queryable(entry: &crate::model::Sequence) -> bool {
    entry.responds.is_some() && entry.replay == "safe"
}

/// Renders the title and per-target capture-date header.
fn render_header(out: &mut String, targets: &[&ResultsFile]) {
    let _ = writeln!(out, "# Terminal support matrix (caniuse)");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "<!-- Generated by `qdb generate reference` from `db/results/*.toml`. Do not edit by hand. -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "This is a rendering of live-capture conformance results, not a hand-claimed support\n\
         table (design 05: machines write support claims; humans write entries and citations).\n\
         Each column names the adapter it was captured through, so its automation level is read,\n\
         not inferred; a capture that falls far behind the freshest one is marked stale rather\n\
         than trusted silently. An unlisted target has no row contribution — no evidence is never\n\
         an assumed pass or fail."
    );
    let _ = writeln!(out);
    if targets.is_empty() {
        let _ = writeln!(out, "No capture results are checked in yet.");
        let _ = writeln!(out);
        return;
    }
    let newest = targets.iter().filter_map(|t| parse_days(&t.captured)).max();
    let _ = writeln!(out, "Captured:");
    let _ = writeln!(out);
    for t in targets {
        // Adapter kind rides along so a reader sees the automation level behind each column
        // (the attended-cell honesty rule) rather than inferring it.
        let adapter = if t.adapter.is_empty() {
            String::new()
        } else {
            format!(", {}", t.adapter)
        };
        let stale = stale_note(&t.captured, newest);
        let _ = writeln!(
            out,
            "- **{}** ({}{adapter}) — {}{stale}",
            t.target, t.version, t.captured
        );
    }
    let _ = writeln!(out);
}

/// The stale annotation for one target's capture date given the set's `newest` day number, or the
/// empty string when the capture is current (or either date is unparsable — we never invent a
/// staleness claim we cannot substantiate).
fn stale_note(captured: &str, newest: Option<i64>) -> String {
    let (Some(days), Some(newest)) = (parse_days(captured), newest) else {
        return String::new();
    };
    let behind = newest - days;
    if behind > STALE_DAYS {
        format!(" — **STALE** ({behind} days behind the freshest capture)")
    } else {
        String::new()
    }
}

/// Parses the `YYYY-MM-DD` date prefix of a capture timestamp into a civil day number (days since
/// 1970-01-01, Howard Hinnant's algorithm). Returns `None` if the prefix is not a valid date, so
/// the caller degrades to "no staleness claim" rather than a wrong one.
fn parse_days(captured: &str) -> Option<i64> {
    let date = captured.get(..10)?;
    let mut parts = date.split('-');
    let y: i64 = parts.next()?.parse().ok()?;
    let m: i64 = parts.next()?.parse().ok()?;
    let d: i64 = parts.next()?.parse().ok()?;
    if !(1..=12).contains(&m) || !(1..=31).contains(&d) {
        return None;
    }
    let y = if m <= 2 { y - 1 } else { y };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let doy = (153 * (if m > 2 { m - 3 } else { m + 9 }) + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    Some(era * 146_097 + doe - 719_468)
}

/// Renders the legend explaining cell verdicts.
fn render_legend(out: &mut String) {
    let _ = writeln!(out, "## Legend");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Verdict | Meaning |");
    let _ = writeln!(out, "| ------- | ------- |");
    let _ = writeln!(
        out,
        "| supported (N) | The target answered with a genuine reply; N is the raw reply byte length. |"
    );
    let _ = writeln!(
        out,
        "| unsupported | Bytes came back but only echoed the query — not a real reply; see `db/README.md`. |"
    );
    let _ = writeln!(
        out,
        "| no-reply | The target ran the probe and produced no reply before the deadline. |"
    );
    let _ = writeln!(
        out,
        "| unprobeable | The entry is a query but the harness will not send it blind (side-effecting or ill-defined); see `db/README.md`. |"
    );
    let _ = writeln!(
        out,
        "| — | No result: this target has not recorded this entry. |"
    );
    let _ = writeln!(out);
}

/// Renders one family table's header row.
fn render_table_header(out: &mut String, targets: &[&ResultsFile]) {
    let _ = write!(out, "| Sequence | id |");
    for t in targets {
        let _ = write!(out, " {} |", t.target);
    }
    let _ = writeln!(out);
    let _ = write!(out, "| --- | --- |");
    for _ in targets {
        let _ = write!(out, " --- |");
    }
    let _ = writeln!(out);
}

/// Renders one entry's row across every target column.
fn render_row(
    out: &mut String,
    entry: &crate::model::Sequence,
    rows_by_target: &[BTreeMap<&str, &ResultRow>],
) {
    let _ = write!(out, "| {} | `{}` |", entry.name, entry.id);
    for rows in rows_by_target {
        let cell: Cell<'_> = rows.get(entry.id.as_str()).copied();
        let _ = write!(out, " {} |", render_cell(cell));
    }
    let _ = writeln!(out);
}

/// Renders one cell's verdict.
fn render_cell(cell: Cell<'_>) -> String {
    match cell {
        None => "—".to_string(),
        Some(row) => match row.verdict.as_str() {
            "supported" => format!("supported ({})", row.reply_len),
            "unsupported" => "unsupported".to_string(),
            "no-reply" => "no-reply".to_string(),
            "unprobeable" => "unprobeable".to_string(),
            "skipped" => match &row.skipped_class {
                Some(class) => format!("skipped ({class})"),
                None => "skipped".to_string(),
            },
            other => format!("unknown ({other})"),
        },
    }
}

/// Renders the compact conformance summary: one row per family with the count of queries each
/// target answered (`supported`) out of the family's queryable entries. This is the docs.rs-facing
/// page — small enough to `include_str!` into the crate docs without bloating it, while the full
/// per-cell verdicts live in [`render`] and the per-family reference pages.
///
/// Deterministic: families in `Database` order, targets sorted by name — the same ordering the full
/// matrix uses, so the freshness check covers this page too.
#[must_use]
pub fn render_summary(db: &Database, results: &[ResultsFile]) -> String {
    let mut targets: Vec<&ResultsFile> = results.iter().collect();
    targets.sort_by(|a, b| a.target.cmp(&b.target));
    let rows_by_target: Vec<BTreeMap<&str, &ResultRow>> = targets
        .iter()
        .map(|t| t.results.iter().map(|r| (r.id.as_str(), r)).collect())
        .collect();

    let mut out = String::new();
    let _ = writeln!(out, "# Terminal conformance summary");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "<!-- Generated by `qdb generate reference` from `db/results/*.toml`. Do not edit by hand. -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Each cell counts the queries a target answered (`supported`) out of the family's\n\
         queryable entries — live-capture evidence, not a hand-claimed table. See the full\n\
         [support matrix](matrix.md) for per-sequence verdicts and the per-family pages for\n\
         citations and fixtures."
    );
    let _ = writeln!(out);
    if targets.is_empty() {
        let _ = writeln!(out, "No capture results are checked in yet.");
        return trim_trailing(out);
    }

    // Header: Family | Queries | <target>...
    let _ = write!(out, "| Family | Queries |");
    for t in &targets {
        let _ = write!(out, " {} |", t.target);
    }
    let _ = writeln!(out);
    let _ = write!(out, "| --- | --- |");
    for _ in &targets {
        let _ = write!(out, " --- |");
    }
    let _ = writeln!(out);

    for family in &db.families {
        let queryable: Vec<&crate::model::Sequence> =
            family.entries.iter().filter(|e| is_queryable(e)).collect();
        if queryable.is_empty() {
            continue;
        }
        let _ = write!(out, "| `{}` | {} |", family.name, queryable.len());
        for rows in &rows_by_target {
            let supported = queryable
                .iter()
                .filter(|e| {
                    rows.get(e.id.as_str())
                        .is_some_and(|r| r.verdict == "supported")
                })
                .count();
            let _ = write!(out, " {supported}/{} |", queryable.len());
        }
        let _ = writeln!(out);
    }
    trim_trailing(out)
}

/// Trims a rendered page to exactly one trailing newline (markdownlint's no-multiple-blanks rule).
fn trim_trailing(mut s: String) -> String {
    while s.ends_with("\n\n") {
        s.pop();
    }
    s
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::model::{Database, Family, Sequence, Source};

    fn entry(id: &str, name: &str, responds: Option<&str>, replay: &str) -> Sequence {
        Sequence {
            id: id.to_string(),
            name: name.to_string(),
            description: "does a thing".to_string(),
            direction: "host-to-terminal".to_string(),
            syntax: None,
            params: Vec::new(),
            refs: Vec::new(),
            fixtures: Vec::new(),
            replay: replay.to_string(),
            responds: responds.map(str::to_string),
            notes: None,
            superseded_by: None,
        }
    }

    fn db_with(families: Vec<Family>) -> Database {
        Database {
            families,
            sources: BTreeMap::<String, Source>::new(),
        }
    }

    fn results(target: &str, version: &str, rows: Vec<ResultRow>) -> ResultsFile {
        ResultsFile {
            target: target.to_string(),
            version: version.to_string(),
            version_source: "hint".to_string(),
            adapter: "pty-headless".to_string(),
            captured: "2026-07-07T10:00:00Z".to_string(),
            runner: "qdb 0.0.0".to_string(),
            geometry: crate::model::Geometry {
                cols: 120,
                rows: 40,
            },
            results: rows,
        }
    }

    fn row(id: &str, verdict: &str, reply_len: usize) -> ResultRow {
        ResultRow {
            id: id.to_string(),
            reply_id: format!("{id}.reply"),
            verdict: verdict.to_string(),
            reply_len,
            skipped_class: None,
        }
    }

    #[test]
    fn only_queryable_entries_become_rows() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![
                entry("test.query", "Test Query", Some("test.reply"), "safe"),
                entry("test.plain", "Test Plain", None, "safe"),
                entry(
                    "test.modal_query",
                    "Modal Query",
                    Some("test.reply2"),
                    "modal",
                ),
            ],
        }]);
        let out = render(&db, &[]);
        assert!(out.contains("test.query"));
        assert!(!out.contains("test.plain"));
        assert!(!out.contains("test.modal_query"));
    }

    #[test]
    fn family_with_no_queryable_entries_is_omitted() {
        let db = db_with(vec![Family {
            name: "quiet".to_string(),
            entries: vec![entry("quiet.one", "Quiet One", None, "safe")],
        }]);
        let out = render(&db, &[]);
        assert!(!out.contains("## `quiet`"));
    }

    #[test]
    fn cell_reports_supported_with_reply_length() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![entry(
                "test.query",
                "Test Query",
                Some("test.reply"),
                "safe",
            )],
        }]);
        let r = results("tmux", "tmux 3.7b", vec![row("test.query", "supported", 6)]);
        let out = render(&db, &[r]);
        assert!(out.contains("supported (6)"));
    }

    #[test]
    fn cell_reports_no_reply() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![entry(
                "test.query",
                "Test Query",
                Some("test.reply"),
                "safe",
            )],
        }]);
        let r = results("tmux", "tmux 3.7b", vec![row("test.query", "no-reply", 0)]);
        let out = render(&db, &[r]);
        assert!(out.contains("| no-reply |"));
    }

    #[test]
    fn cell_reports_skipped_with_class() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![entry(
                "test.query",
                "Test Query",
                Some("test.reply"),
                "safe",
            )],
        }]);
        let mut skipped = row("test.query", "skipped", 0);
        skipped.skipped_class = Some("modal".to_string());
        let r = results("tmux", "tmux 3.7b", vec![skipped]);
        let out = render(&db, &[r]);
        assert!(out.contains("| skipped (modal) |"));
    }

    #[test]
    fn missing_target_result_renders_dash() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![entry(
                "test.query",
                "Test Query",
                Some("test.reply"),
                "safe",
            )],
        }]);
        // A target file exists but never probed this particular entry.
        let r = results("tmux", "tmux 3.7b", vec![]);
        let out = render(&db, &[r]);
        assert!(out.contains("| — |"));
    }

    #[test]
    fn targets_sorted_by_name_regardless_of_input_order() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![entry(
                "test.query",
                "Test Query",
                Some("test.reply"),
                "safe",
            )],
        }]);
        let betamax = results(
            "betamax",
            "libghostty",
            vec![row("test.query", "supported", 5)],
        );
        let tmux = results("tmux", "tmux 3.7b", vec![row("test.query", "supported", 6)]);
        // Pass betamax first; header and table columns must still read tmux before betamax... no,
        // alphabetically betamax < tmux, so betamax leads.
        let out = render(&db, &[tmux, betamax]);
        let header_line = out
            .lines()
            .find(|l| l.starts_with("| Sequence | id |"))
            .unwrap();
        let betamax_pos = header_line.find("betamax").unwrap();
        let tmux_pos = header_line.find("tmux").unwrap();
        assert!(betamax_pos < tmux_pos);
    }

    #[test]
    fn empty_results_renders_no_captures_notice() {
        let db = db_with(vec![]);
        let out = render(&db, &[]);
        assert!(out.contains("No capture results are checked in yet."));
    }

    #[test]
    fn unprobeable_status_renders_as_unprobeable() {
        let db = db_with(vec![Family {
            name: "test".to_string(),
            entries: vec![entry(
                "test.query",
                "Test Query",
                Some("test.reply"),
                "safe",
            )],
        }]);
        let r = results(
            "tmux",
            "tmux 3.7b",
            vec![row("test.query", "unprobeable", 0)],
        );
        let out = render(&db, &[r]);
        assert!(out.contains("| unprobeable |"));
    }
}
