//! @generated by `qdb width-table` from `db/width/*.toml` — do not edit.
//!
//! The per-terminal grapheme-cluster width deviations from the static unicode-width
//! baseline (design 09-width). Freshness is enforced by a qdb test; regenerate with
//! `qdb width-table`. Only clusters that deviate are listed; everything else is the
//! baseline.

use crate::caps::TerminalProgram;

/// One cluster whose rendered advance differs from `unicode-width` on a given terminal.
pub(crate) struct Deviation {
    /// The grapheme cluster.
    pub text: &'static str,
    /// Measured advance with mode 2027 off/unset.
    pub advance: usize,
    /// Measured advance with mode 2027 on, when the terminal honours it.
    pub advance_2027: Option<usize>,
}

/// A terminal's width deviations, keyed on its identity program.
pub(crate) struct Profile {
    /// The terminal program this profile applies to.
    pub program: TerminalProgram,
    /// The clusters that deviate from the baseline on this terminal.
    pub deviations: &'static [Deviation],
}

/// Every terminal profile with measured width deviations.
pub(crate) static PROFILES: &[Profile] = &[
    Profile {
        program: TerminalProgram::Alacritty,
        deviations: &[
        Deviation { text: "\u{2764}\u{FE0F}", advance: 1, advance_2027: None },
        ],
    },
    Profile {
        program: TerminalProgram::Ghostty,
        deviations: &[
        Deviation { text: "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}", advance: 8, advance_2027: Some(2) },
        Deviation { text: "\u{1F44D}\u{1F3FD}", advance: 4, advance_2027: Some(2) },
        Deviation { text: "\u{1F1FA}\u{1F1F8}", advance: 4, advance_2027: Some(2) },
        Deviation { text: "\u{2764}\u{FE0F}", advance: 1, advance_2027: Some(2) },
        ],
    },
    Profile {
        program: TerminalProgram::Kitty,
        deviations: &[
        Deviation { text: "\u{1F44D}\u{1F3FD}", advance: 2, advance_2027: None },
        ],
    },
    Profile {
        program: TerminalProgram::Tmux,
        deviations: &[
        Deviation { text: "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}", advance: 2, advance_2027: None },
        Deviation { text: "\u{1F44D}\u{1F3FD}", advance: 2, advance_2027: None },
        ],
    },
    Profile {
        program: TerminalProgram::WezTerm,
        deviations: &[
        Deviation { text: "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}", advance: 2, advance_2027: None },
        Deviation { text: "\u{1F44D}\u{1F3FD}", advance: 2, advance_2027: None },
        Deviation { text: "\u{2764}\u{FE0F}", advance: 1, advance_2027: None },
        ],
    },
];
